name: TexturePacker

on:
  push:
    paths:
      - .github/workflows/texturepacker.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      TEXTUREPACKER_TAG: ghcr.io/snowcait/texturepacker:5.5.0

    steps:
#       - run: ls -la
#       - name: Pull
#         run: docker pull ${TEXTUREPACKER_TAG}
#       - run: docker images
      - name: License agreement
        run: docker run ${TEXTUREPACKER_TAG} TexturePacker
#       - name: Help
#         run: docker run ${TEXTUREPACKER_TAG} TexturePacker --help
#       - name: Version
#         run: docker run ${TEXTUREPACKER_TAG} TexturePacker --version
#       - name: License
#         run: docker run ${TEXTUREPACKER_TAG} TexturePacker --license-info
#       - name: License
#         run: docker run ${TEXTUREPACKER_TAG} TexturePacker --activate-license ${LICENSE_KEY} --license-info
#         env:
#           LICENSE_KEY: ${{ secrets.TEXTUREPACKER_LICENSE_KEY }}
#       - name: Spritesheet
#         run: |
#           docker run ${TEXTUREPACKER_TAG} \
#           --mount type=bind,source=/tmp/spritesheets,target=/spritesheets \
#           TexturePacker --activate-license ${LICENSE_KEY} /spritesheets/*.tps
#         env:
#           LICENSE_KEY: ${{ secrets.TEXTUREPACKER_LICENSE_KEY }}
